apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: lms
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP             # internal only — not exposed to internet
