apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-config
  namespace: lms
data:
  MYSQL_HOST: "lms-eks-cluster-mysql.c8d64ucku0mx.us-east-1.rds.amazonaws.com"
  MYSQL_USER: "lmsadmin"
  MYSQL_DB: "online_exam"
  FLASK_ENV: "production"
  MYSQL_SSL: "true"