name: Auto Deploy to EKS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lms-app
  EKS_CLUSTER_NAME: lms-eks-cluster
  K8S_NAMESPACE: lms

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin \
        694630903450.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Image
      run: |
        docker build -t lms-app:latest .

    - name: Tag Image
      run: |
        docker tag lms-app:latest \
        694630903450.dkr.ecr.$AWS_REGION.amazonaws.com/lms-app:latest

    - name: Push Image
      run: |
        docker push 694630903450.dkr.ecr.$AWS_REGION.amazonaws.com/lms-app:latest

    - name: Connect to EKS
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $EKS_CLUSTER_NAME

    - name: Update Deployment Image
      run: |
        kubectl set image deployment/lms-app \
        lms-app=694630903450.dkr.ecr.$AWS_REGION.amazonaws.com/lms-app:latest \
        -n $K8S_NAMESPACE

    - name: Restart Deployment (important)
      run: |
        kubectl rollout restart deployment/lms-app -n $K8S_NAMESPACE

    - name: Wait for rollout (stable)
      run: |
        kubectl rollout status deployment/lms-app \
        -n $K8S_NAMESPACE \
        --timeout=600s || true