apiVersion: v1
kind: Secret
metadata:
  name: lms-secret
  namespace: lms
type: Opaque
data:
  MYSQL_PASSWORD: TG1zMjAyNmlzYSE=
  SECRET_KEY: NGNmMDAzYzI2ODFjYmJjZjk5ZTZhZGE1OGUzODc3YTIzMDgwMTdjZjVmZjMwOGI0NDY1MTIxZmVmMWY5MzVkOQ==