name: Debug Cluster
on: [push]
env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: lms-eks-cluster
  K8S_NAMESPACE: lms

permissions:
  id-token: write
  contents: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::841162688057:role/github-actions-eks-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect to EKS
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Collect Logs
        run: |
          echo "==== PODS ====" > all.txt
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} >> all.txt 2>&1
          echo "==== SECRETS ====" >> all.txt
          kubectl get secrets -n ${{ env.K8S_NAMESPACE }} >> all.txt 2>&1
          echo "==== CM ====" >> all.txt
          kubectl get cm -n ${{ env.K8S_NAMESPACE }} >> all.txt 2>&1
          echo "==== DESCRIBE PODS ====" >> all.txt
          kubectl describe pods -l app=lms-app -n ${{ env.K8S_NAMESPACE }} >> all.txt 2>&1
          echo "==== LOGS ====" >> all.txt
          kubectl logs -l app=lms-app -n ${{ env.K8S_NAMESPACE }} --all-containers --max-log-requests=6 --tail=300 >> all.txt 2>&1 || true

      - name: Commit and Push Logs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b debug-logs
          mv all.txt k8s-debug-logs.txt
          git add k8s-debug-logs.txt
          git commit -m "add k8s debug logs"
          git push origin debug-logs --force
